Repository Bamdoliro/Gati-app, pull requests merged in 2022-11, with the labels that each got.

#45 SET :: code owners (#38)
  .github/CODEOWNERS
Labels: ⚙️ Setting

#55 Feat/auth
  .gitignore
  App.js
  TabNavigation.js
  hooks/useSocket.js
  pages/ChatListScreen.js
  pages/ChatLiveScreen.js
  pages/LoginScreen.js
  patches/react-native+0.69.5.patch
  utils/api/urls.js
Labels: ✨ Feature

#62 Feat/write post
  package-lock.json
  package.json
  src/assets/BlueCalender.png
  src/assets/GrayGati.png
  src/assets/WhiteGati.png
  src/components/Community/CommunityHeader/CommunityHeader.js
  src/components/Community/create/PublicScopeArea.js
  src/components/CommunityPostPage/GatiPostList/GatiPostList.js
  src/components/CommunityPostPage/ListFrame/GatiFrame.js
  src/components/CommunityPostPage/ListFrame/PostFrame.js
  src/components/CommunityPostPage/PostList/PostList.js
  src/components/MainPage/.gitkeep
  src/components/common/BasicInput/BasicInput.js
  src/components/common/DateInput/DateInput.js
  src/components/common/FrameInput/FrameInput.js
  src/components/common/GatiButton/GatiButton.js
  src/components/common/GatiIntroduction/GatiIntroduction.js
  src/components/common/Header/Header.js
  src/components/common/InputFrame/InputFrame.js
  src/components/common/NumberOfPeopleInput/NumberOfPeopleInput.js
  src/components/common/Option/Option.js
  src/components/common/OptionBtn/OptionBtn.js
  src/components/common/PeriodInput/PeriodInput.js
  src/components/common/PlusButton/PlusButton.js
  src/components/common/TextArea/TextArea.js
  src/components/common/UploadImgContent/UploadImgContent.js
  src/data/GatiListData.json
  src/data/PostListData.json
  src/routes/MainNavigation.js
  src/screens/CommunityScreen.js
  src/screens/EmailAuthScreen.js
  src/screens/GatiProduceScreen.js
  src/screens/HomeScreen.js
  src/screens/Post/write/WriteGatiScreen.js
  src/screens/Post/write/WritePostScreen.js
  src/screens/ProduceCommunityScreen.js
Labels: ✨ Feature, 🔨 Refactor

#68 CHORE :: 배너 수정 (#67)
  package-lock.json
  package.json
  src/assets/banner/banner1.png
  src/assets/banner/banner2.png
  src/assets/banner/banner3.png
  src/components/Home/Banner/Banner.js
Labels: 🏓 Chore

#70 Feat/change community modal
  App.js
  babel.config.js
  package-lock.json
  package.json
  src/components/Community/ChangeCommunity/ChangeCommunityModal.js
  src/components/Community/ChangeCommunity/Community.js
  src/components/Community/CommunityHeader/CommunityHeader.js
  src/data/MyCommunityList.json
  src/screens/CommunityScreen.js
  yarn.lock
Labels: ✨ Feature

#73 FIX :: borderRadius: 50% 에러 수정
  src/components/Community/CommunityHeader/CommunityHeader.js
  src/components/Home/Banner/Banner.js
  src/components/common/input/Select/Select.js
  src/routes/MainNavigation.js
  src/screens/CommunityPostWritingScreen.js
  yarn.lock
Labels: 🐞 Bug
